
lang: cs
title: JihoČAS
email: romandvorak@mlab.cz
description: >- # this means to ignore newlines until "baseurl:"
  JihoČAS stránka
baseurl: "/JihoCAS-homepage" # the subpath of your site, e.g. /blog
url: "https://jihoCAS.github.io"
#twitter_username: jekyllrb
github_username:  AstroMeters
permalink: pretty
theme_color: '#1c305c'

# Build settings
markdown: kramdown
#theme: just-the-docs
theme: bulma-clean-theme@1.0.0
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from


collections:
  products: 
    output: true
    image: ''
    show_sidebar: false
