lang: cs
title: JihoČAS
email: romandvorak@mlab.cz
description: >- # this means to ignore newlines until "baseurl:"
  Jihočeská pobočka České astronomické společnosti – popularizace astronomie,
  pozorovací projekty a spolupráce jihočeských hvězdáren.
baseurl: "/JihoCAS-homepage" # the subpath of your site, e.g. /blog
url: "https://jihocas.github.io"
github_username: AstroMeters
permalink: pretty
theme_color: '#1c305c'
timezone: Europe/Prague

# Build settings
markdown: kramdown
theme: bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

hide_share_buttons: true
footer_menu: footer_menu

collections:
  projekty:
    output: true
    permalink: /projekty/:name/

logo: /assets/img/logo-cas-kulate-modre.png

defaults:
  - scope:
      path: ""
    values:
      layout: page
      show_sidebar: false
      image: /assets/img/og-image.png
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_sidebar: false
  - scope:
      path: ""
      type: projekty
    values:
      layout: page
      hero_height: is-small

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
